### ISSUE TITLE
Checklist: Plus Release - 2.8.0

### ISSUE THREAD

**Issue by Sunderlandkyl** [PlusToolkit/PlusLib#482]
Checklist from: https://github.com/PlusToolkit/PlusBuild/blob/master/Docs/NewReleaseChecklist.md

### PlusBuild
  - [x] Create a new branch from the trunk as Plus-X.Y
  - [x] In the new branch:
    - [x] Update PLUSBUILD_PLUSLIBDATA_GIT_REVISION from master to Plus-X.Y
    - [x] Update PLUSLIB_GIT_REVISION from master to Plus-X.Y
    - [x] Update PLUSLIB_GIT_REVISION from master to Plus-X.Y
    - [x] Update PLUSAPP_GIT_REVISION from master to Plus-X.Y
    - [x] Update SetGitRepositoryTag in dependencies to reference the latest commit of third-party software:
      - [x] External_OpenIGTLink
      - [x] External_OpenIGTLinkIO
      - [x] External_OvrvisionPro
      - [x] External_Tesseract
      - [x] External_aruco
      - [x] External_ndicapi
      - [x] Any other dependencies that refer to 'master' version instead of a specific git tag or hash

### PlusLib
  - [x] Create a new branch from the trunk as Plus-X.Y
  - [x] In the new branch:
    - [x] Update minor version number to Y in CmakeLists.txt
  - [ ] In the trunk:
    - [ ] Update minor version number to Y+1 in CmakeLists.txt

### PlusApp
  - [x] Create a new branch from the trunk as Plus-X.Y

### PlusLibData
  - [x] Create a new branch from the trunk as Plus-X.Y

### Build scripts
  - [x] Update PLUS_STABLE_VERSION in CommonVars.bat to version X.Y

## Test the new release

Double-check that all main features of Plus work before releasing stable build. See the "test plan" below. It would be nice to add more details (what config file was used, etc) as the test is performed. The test report would be used as a template for testing the next stable release (probably it would make sense to add to the PlusLib or PlusApp repository).

### Mandatory tests

- [x] Green dashboard (no build or test errors):
  - Windows
    - [x] PlusBuild
    - [x] PlusApp
    - [x] PlusLib
  - Linux
    - [x] PlusBuild
    - [x] PlusApp
    - [x] PlusLib
    - Note: Only failing tests are related to display connection
  - [x] Failing or unstable tests: ___
- [x] Plus runs on Ultrasonix (Windows XP Embedded):
  - [x] Slicer version: Slicer 4.10.1
  - [x] Ultrasound exam software version: Sonix 6.1.1
  - [x] Ultrasound probe: Ultrasonix C5-2
  - [x] Live image is displayed in Slicer
  - [x] Start/stop recording works in Slicer using PlusRemote
  - [x] Scout scan and live volume reconstruction works in Slicer using PlusRemote
- [x] Tracking using NDI Polaris
- [x] Tracking using NDI Aurora
- [x] Tracking using PhidgetSpatial
- [x] Ultrasound imaging using Interson
- [x] Ultrasound imaging using Telemed
- [x] Image acquisition using Epiphan
- [x] Image acquisition using webcam - Video for Windows
  - Fails with application verifier enabled, happens with 2.6 and 2.4 as well
- [x] Grayscale image acquisition using webcam - MMF
- [x] Color image acquisition using webcam - MMF
- [x] Image acquisition using ImagingControls
  - ~~Returns the same image as the demo application. Need to find an S-Video or Composite device that outputs a clear image~~ Works: Tested with a better device
  - Crash on exit. Happens in 2.6 stable as well, so it's not a blocking issue.
- [x] Tracking using StealthLink
  - [x] Make sure to test image retrieve using OpenIGTLinkRemote
- [x] Tracking using OpticalMarkerTracking
- [x] Tracking using OptiTrack
- [x] Replay of tracked video from saved data source
- [x] US simulator using Slicer scene in DataStore
  - ~~Image updates as expected, however update of *ToReference transforms is significantly delayed compared to Image_Reference ~~ -- Fixed
- [x] OpenIGTLinkTracker
- [x] OpenIGTLinkVideo
- [x] ThorLabs spectrometer
- [x] Test that user manual is available in the installed package (doc\PlusApp-UserManual.chm)
- [x] Test compressed video streaming with Slicer
- [ ] Test remote control of Plus from Slicer (Plus Remote module in SlicerOpenIGTLink)

### Outstanding issues
- [x] Investigate issues with PlusRemote (See https://discourse.slicer.org/t/unable-to-input-channel-id-in-slicer-igt-plus-remote/5799/6)
- [x] PlusServer crashes when recording mha/mhd with only transforms, and has to be force terminated if recording nrrd (Tested using EnableCapturingOnStart="TRUE")

## Finalize release

- [x] Upload stable release installation packages to release download server
- [x] Update this documentation to reflect any changes in the release process
- [x] Create release on GitHub and upload packages
